# Site settings
title: Hollanda'da Yaşam
description: >- # this means to ignore newlines until "baseurl:"
  Hollanda'da yaşama dair sıkça sorulan sorular, merak edilenler
url: "https://www.hollandadayasam.com"
github_username:  altanpazarli

# Build settings
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Aux links for the upper right navigation
aux_links:
  "Kahve ısmarla":
    - "//buymeacoffee.com/altanpazarli"
  "Github'da katkıda bulun":
    - "//github.com/altanpazarli/hollandada-yasam"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Google Analytics Tracking
ga_tracking: G-7KGQE79SSQ
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings